### ISSUE TITLE
add list of binaries built

### ISSUE THREAD

**Issue by maelle** [r-universe-org/hitchhikers-guide#19]
@jeroen where do I find a list for https://github.com/r-universe-org/hitchhikers-guide/blob/be74289636393a6361b17739c58abcfb217b1d59/publish/get-started.qmd#L13 or do I just write "for major OS" and a link to https://docs.r-universe.dev/install/binaries.html?

**Comment by jeroen** [comment]
Yes, it is a moving target so we should just say release versions for the most popular platforms.
