### ISSUE TITLE
Document app permissions and commit status updates

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/hitchhikers-guide#7]
See https://github.com/r-universe-org/help/discussions/407

**Comment by maelle** [comment]
in https://docs.r-universe.dev/publish/set-up.html 

maybe the first paragraphs should get a section title :thinking:

**Comment by maelle** [comment]
10.3 and 10.4 already have the info and a screenshot, actually https://docs.r-universe.dev/publish/set-up.html

**Comment by maelle** [comment]
Please re-open if anything is missing.
